server:
  port: 8080

spring:
  application:
    name: mongodb-testcontainer-example
  data:
    mongodb:

#      authentication-database: admin
#      username: root
#      password: root
#      database: test_db
#      port: 27017
#      host: localhost
#      database: reactive
      uri: mongodb://localhost:27017/reactive
  activemq:
    packages:
      trust-all: true

